module SRX
  module Polish
    module Rules
      def rules
        @@rules ||=
[["(?:\\b[Aa]dw?\\.\\s)|(?:\\bafr\\.\\s)|(?:\\bakad\\.\\s)|(?:\\b[Aa]l\\.\\s)|(?:\\bam\\.\\s)|(?:\\bamer\\.\\s)|(?:\\barch\\.\\s)|(?:\\b[Aa]rt\\.\\s)|(?:\\bartyst\\.\\s)|(?:\\bastr\\.\\s)|(?:\\baustr\\.\\s)|(?:\\bbałt\\.\\s)|(?:\\bbdb\\.\\s)|(?:\\bbł\\.\\s)|(?:\\bbm\\.\\s)",
  nil,
  false],
 ["(?:\\bbr\\.\\p{Pe}?\\s)", "[^\\p{Lu}]", false],
 ["(?:\\bbry[gt]\\.\\s)|(?:\\bcentr\\.\\s)|(?:\\bces\\.\\s)|(?:\\bchem\\.\\s)|(?:\\bchiń\\.\\s)|(?:\\bchir\\.\\s)|(?:\\bc\\.k\\.\\s)|(?:\\bc\\.o\\.\\s)|(?:\\bcyg\\.\\s)|(?:\\bcyw\\.\\s)|(?:\\bcyt\\.\\s)|(?:\\bczes\\.\\s)|(?:\\bczw?\\.\\s)|(?:\\b[Cc]d\\.\\s)|(?:\\bczyt\\.\\s)|(?:\\bćw\\.\\s)|(?:\\bćwicz\\.\\s)|(?:\\bdaw\\.\\s)|(?:\\bdcn\\.\\s)|(?:\\bdekl\\.\\s)|(?:\\bdemokr\\.\\s)|(?:\\bdet\\.\\s)|(?:\\bdiec\\.\\s)|(?:\\bdł\\.\\s)|(?:\\bdn\\.\\s)",
  nil,
  false],
 ["(?:\\bdo[tlp]\\.\\s)", "[^\\p{Lu}]", false],
 ["(?:\\bdost\\.\\s)|(?:\\bdosł\\.\\s)|(?:\\bh\\.c\\.\\s)|(?:\\bds\\.\\s)|(?:\\bdst\\.\\s)|(?:\\bduszp\\.\\s)|(?:\\bdypl\\.\\s)|(?:\\begz\\.\\s)|(?:\\bekol\\.\\s)|(?:\\bekon\\.\\s)|(?:\\belektr\\.\\s)|(?:\\bem\\.\\s)|(?:\\bew\\.\\s)|(?:\\bfab\\.\\s)|(?:\\bfarm\\.\\s)|(?:\\bfot\\.\\s)|(?:\\bfr\\.\\s)|(?:\\bgat\\.\\s)|(?:\\bgastr\\.\\s)|(?:\\bgeogr\\.\\s)|(?:\\bgeol\\.\\s)|(?:\\bgimn\\.\\s)|(?:\\bgłęb\\.\\s)|(?:\\bgm\\.\\s)|(?:\\bgodz\\.\\s)|(?:\\bgórn\\.\\s)|(?:\\bgosp\\.\\s)|(?:\\bgr\\.\\s)|(?:\\bgram\\.\\s)|(?:\\bhist\\.\\s)|(?:\\bhiszp\\.\\s)|(?:\\b[Hh]r\\.\\s)|(?:\\bhot\\.\\s)|(?:\\bid\\.\\s)|(?:\\bin\\.\\s)|(?:\\bim\\.\\s)|(?:\\biron\\.\\s)|(?:\\bjn\\.\\s)|(?:\\bkard\\.\\s)|(?:\\bkat\\.\\s)|(?:\\bkatol\\.\\s)|(?:\\bk\\.k\\.\\s)|(?:\\bkk\\.\\s)|(?:\\bko?l\\.\\s)|(?:\\bk\\.p\\.a\\.\\s)|(?:\\bkpc\\.\\s)|(?:\\bk\\.p\\.c\\.\\s)|(?:\\bkpt\\.\\s)|(?:\\bkr\\.\\s)|(?:\\bk\\.r\\.\\s)|(?:\\bkrak\\.\\s)|(?:\\bk\\.r\\.o\\.\\s)|(?:\\bkryt\\.\\s)|(?:\\bkult\\.\\s)|(?:\\blaic\\.\\s)|(?:\\błac\\.\\s)|(?:\\bniem\\.\\s)|(?:\\bwoj\\.\\s)|(?:\\b[Nn][bp]\\.\\s)|(?:\\bpo[lw]\\.\\s)|(?:\\bm\\.in\\.\\s)|(?:\\b[Pp][ts]\\.\\s)|(?:\\bcdn\\.\\s)|(?:\\bjw\\.\\s)|(?:\\b[Rr]y[cs]\\.\\s)|(?:\\btj\\.\\s)|(?:\\b[Tt]zw\\.\\s)|(?:\\btzn\\.\\s)|(?:\\b[Zz]ob\\.\\s)|(?:\\bsłow\\.\\s)",
  nil,
  false],
 ["(?:[^s]\\.pl\\.\\s)", "\\p{Lu}\\p{Ll}+", true],
 ["(?:\\bp[wnl]\\.\\s)|(?:\\bang\\.\\s)|(?:\\bu[lb]\\.\\s?)|(?:\\bal\\.\\s)|(?:\\bk\\.\\s)|(?:\\bn\\.\\s)",
  nil,
  false],
 ["(?:\\b[Oo]k\\.\\s)", "[\\p{Ll}\\d]", false],
 ["(?:\\b[\\d,\\.]*ty[sś]\\.\\p{Pe}?\\s)", "[\\p{Ll}\\d]+", false],
 ["(?:\\b[Nn]r\\.\\s)", "\\d", false],
 ["(?:\\bw[wł]\\.\\s)|(?:\\bur\\.\\s)|(?:\\bzm\\.\\s)|(?:\\bżyd\\.\\s)|(?:\\bżarg\\.\\s)|(?:\\bżyw\\.\\s)|(?:\\bwy[łdm]\\.\\s)|(?:\\b[bu]p\\.\\s)|(?:\\bwyst\\.\\s)",
  nil,
  false],
 ["(?:\\b(?i)mazeł\\stow\\.\\s)", nil, true],
 ["(?:\\b[Tt]ow\\.\\s)|(?:\\bo\\.\\s)|(?:\\b(?:[sS]p|st|[Ss]półdz|społ|spółgł|[Ss]to[łw])\\.\\s)|(?:\\bzn\\.\\s)|(?:\\bzew\\.\\s)|(?:\\bzewn\\.\\s)|(?:\\bzdr\\.\\s)|(?:\\bzazw\\.\\s)|(?:\\bzast\\.\\s)|(?:\\bzaw\\.\\s)|(?:\\bzał\\.\\s)|(?:\\bzal\\.\\s)|(?:\\bzam\\.\\s)|(?:\\bzak\\.\\s)|(?:\\bzakł\\.\\s)|(?:\\bzagr\\.\\s)|(?:\\bzach\\.\\s)|(?:\\b[Aa]dw\\.\\s)|(?:\\b[Ll]ek\\.\\s)|(?:\\bmed\\.\\s)|(?:\\b[Mm]ec\\.\\s)|(?:\\b[Dd]oc\\.\\s)|(?:\\b[Dd]y[wr]\\.\\s)|(?:\\b[Ii]nż\\.\\s)|(?:\\b(?i)mgr\\.\\s)|(?:\\b[dD][hr]\\.\\s)",
  nil,
  false],
 ["(?:\\b[pP]\\.\\s)", "\\p{Lu}\\p{Ll}+", false],
 ["(?:\\b[Rr]ed\\.\\)?\\s)|(?:\\b(?i)pro[fk]\\.\\s)|(?:\\bhab\\.\\s)|(?:\\b[Pp]łk\\.\\s)|(?:\\b(?:[Nn]a|[Pp]o)dkom\\.\\s)|(?:\\b[kK]s\\.\\s)|(?:\\b(?i)gen\\.\\s)|(?:\\b(?i)por\\.\\s)|(?:\\b[Rr]eż\\.\\s)|(?:\\b[Pp]rzyp\\.\\s)|(?:\\bp\\.n\\.e\\.\\s)|(?:\\bdyr\\.\\smuz\\.\\s)|(?:\\b[śŚ][pwW]\\.\\s)",
  nil,
  false],
 ["(?:\\bII?\\społ\\.\\s)", "[IVX]+", false],
 ["(?:\\betc\\.\\s)", "\\p{Ll}", false],
 ["(?:\\bit[dp]\\.\\s)", "[„”\"]?\\p{Ll}", false],
 ["(?:\\bproc\\.\\)?\\s)", "\\p{Ll}|\\p{Lu}\\p{Lu}+", false],
 ["(?:\\b[rwn]\\.\\s)|(?:\\bit[dp]\\.\\s)|(?:\\bcdn\\.\\s)", "\\p{Ll}", false],
 ["(?:\\b[Ss]zer\\.\\s)", nil, false],
 ["(?:\\bjw\\.\\s)|(?:\\bn\\.e\\.\\s)|(?:\\bw\\.\\s)|(?:\\bn[tn]\\.\\s)|(?:\\b[dm]l\\.\\s)|(?:\\bdag\\.\\s)|(?:\\b[cd]?m\\.\\s)|(?:\\b[Zz][Łł]\\.\\s)|(?:\\b[Gg][rR]\\.\\s)|(?:\\b[d]?kg\\.\\s)|(?:\\bml[nd]\\.\\s)|(?:\\bnpl\\.\\s)",
  "\\p{Ll}",
  false],
 ["(?:\\bpkt\\.\\s)|(?:\\bstr\\.\\s)|(?:\\b[Tt]ab\\.\\s)",
  "[\\p{Ll}\\d]",
  false],
 ["(?:\\btel\\.\\s)", nil, false],
 ["(?:\\b[ptw]g\\.\\s)|(?:\\bcos\\.\\s)|(?:\\bcosec\\.\\s)|(?:\\bsec\\.\\s)|(?:\\bsin\\.\\s)|(?:\\brkm\\.\\s)",
  "\\p{Ll}",
  false],
 ["(?:\\bust\\.\\s)|(?:\\bpar\\.\\s)", "\\d", false],
 ["(?:\\blit\\.\\s)", "\\p{Ll}\\p{Pe}?\\p{P}?\\s", false],
 ["(?:\\b[Pp]on\\.\\s)|(?:\\b[Ss]ob\\.\\s)|(?:\\bba!\\s)", "\\p{Ll}", false],
 ["(?:\\bpo[zk]\\.\\s)", nil, false],
 ["(?:\\bop\\.\\s)", "cit\\.", false],
 ["(?:\\b[Oo][Oo]\\.\\s)", nil, false],
 ["(?:\\b(?:[CDSR]z|Ch)\\.\\s)", "\\p{Ll}", false],
 ["(?:\\b[rls]\\.\\s)", "[1-9]+", false],
 ["(?:\\((?:od|do|w)\\s[1-9]\\d*\\sr\\.\\s)", nil, false],
 ["(?:\\d+\\sr\\.\\s)|(?:\\bn\\.e\\.\\s)", "[^\\p{Lu}]", false],
 ["(?:\\bt\\.\\s)", "\\d+", false],
 ["(?:\\b[,uoi]\\ss\\.\\s)|(?:\\b[Nn]ajśw\\.\\s)|(?:\\b[Nn]a\\sos\\.\\s)",
  nil,
  false],
 ["(?:\\bT\\.)", "Love\\b", false],
 ["(?:\\bpl\\.)", "Open[oO]ffice", false],
 ["(?:\\bha\\.\\s)", "[\\p{Ll}]", false],
 ["(?:\\bmin\\.\\s)", "[\\p{Ll}\\d]", false],
 ["(?:\\bW\\s\\d{4}\\sr\\.\\s)", "[\\p{Lu}–—„\"-]", false],
 ["(?:\\b\\d+\\.\\s)", "\\p{Ll}|\\p{Lu}{2,}", false],
 ["(?:\\b\\p{L}\\.\\s)", "\\p{L}\\.\\s", false],
 ["(?:\\b\\p{L}\\.)", "\\p{L}\\.", false],
 ["(?:\\.\\p{L}+\\.\\s)", "\\p{Ll}", false],
 ["(?:[\\s\\(\\[][\\p{L}&&[^rwn]]\\.\\s+)",
  "\\p{Ll}\\p{Ll}|\\p{Lu}[\\p{Punct}\\p{Lu}]",
  false],
 ["(?:['\"„][\\.!?…]['\"”]\\s)", nil, false],
 ["(?:[\"”']\\s*)", "\\s*\\p{Ll}", false],
 ["(?:[!?]+\\p{Pe} )", "\\p{Ll}", false],
 ["(?:[\\p{Ps}][!?]+[\\p{Pe}] )", nil, false],
 ["(?:[\\[\\(]*\\.\\.\\.[\\]\\)]* )|(?:[\\[\\(]*…[\\]\\)]* )",
  "\\p{Ll}",
  false],
 ["(?:\\b\\p{Lu}\\.\\s\\p{Lu}\\.\\s)|(?:\\b\\p{Lu}\\.\\p{Lu}\\.\\s)",
  nil,
  false],
 ["(?:\\b\\p{Lu}\\p{Ll}\\.\\s?)|(?:\\.\\p{Lu}\\p{Ll}\\.\\s?)",
  "\\p{Lu}[^\\p{Lu}]",
  false],
 ["(?:\\s(?<!\\.)[„\"\\p{Ps}]?[A-Z]\\.\\s)|(?:^[„\"]?[A-ZŚĆŻŹ]\\.\\s)",
  "\\p{Ll}|\\p{Lu}\\p{Ll}\\p{Ll}+",
  false],
 ["(?:\\(\\p{Lu}?\\p{Ll}+\\.\\s)", nil, false],
 ["(?:\\s[A-Z]\\.\\s)", "\\(\\d", false],
 ["(?:\\bDz\\.\\s?U\\.\\s)", nil, false],
 ["(?:[\\p{Ll}&&[^aeouiyęąó]][\\p{Ll}&&[^aeouiyęąó]]+\\.\\s)",
  "\\p{Ll}+",
  false],
 ["(?:[\\.!?…]+['\"\\p{Pe}\\u00BB\\u2019\\u201D\\u203A\\u0002]*\\s)",
  "[\\p{Ps}–—-]\\s?\\p{Ll}",
  false],
 ["(?:[\\.!?…]['\"\\u00BB\\u2019\\u201D\\u203A\\u0002]*\\p{Pe}\\s)",
  "\\p{Ll}",
  false],
 ["(?:[\\.!?…]['\"\\p{Pe}\\u00BB\\u2019\\u201D\\u203A\\u0002¹²³]*\\s)",
  nil,
  true],
 ["(?:[\\.!?…]['»\"”\\p{Pe}]*)", "\\p{Lu}[^\\p{Lu}\\.]", true],
 ["(?:\\s\\p{L}[\\.!?…]\\s)", "\\p{Lu}\\p{Ll}", true],
 ["(?:: )", "[—\\-–] \\p{Lu}", true]]
      end
    end
  end
end
